[project]
name = "cukcuk"
version = "0.4.2"
description = "Connect to Cukcuk Shop API"
authors = [{ name = "Minh Bui", email = "buiducminh287@gmail.com" }]
dependencies = ["requests >= 2", "sqlalchemy >= 2", "pytz"]
