[project]
name = "cukcuk"
version = "0.1.0"
description = "Connect to Cukcuk Shop API"
authors = [{ name = "Minh Bui", email = "buiducminh287@gmail.com" }]
packages = [{ include = "cukcuk" }, { include = "cukcuk/*.py" }]
dependencies = ["requests >= 2", "sqlalchemy >= 2", "pytz"]
