name: "Upload to PyPI"

on:
  push:
    branches:
      - "master"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/cukcuk-sdk
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
