name: "Upload to PyPI"

on:
  push:
    branches:
      - "master"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/cukcuk-sdk
    permissions:
      id-token: write
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.6.0

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://pypi.org/p/cukcuk-sdk/
